server:
  port: ${SERVER_PORT:8081}
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:user-service}
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI}
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: neo4j
      password: ${NEO4J_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 2
      timeout: ${REDIS_TIME_OUT}
      lettuce:
        pool:
          max-active: ${MAX_ACTIVE}
          max-idle: ${MAX_IDLE}
          min-idle: ${MIN_IDLE}

  cache:
    type: redis

keycloak:
  admin:
    server-url: ${KEYCLOAK_URL}
    realm: ${KEYCLOAK_REALM}
    client-id: ${KEYCLOAK_CLIENT_ID_SERVICE}
    client_secret: ${KEYCLOAK_CLIENT_SECRET_SERVICE}
encryption:
  field-key: ${FIELD_ENCRYPTION_KEY}
  hmac-key: ${FIELD_ENCRYPTION_HMAC_KEY}

app:
  services:
    profile: ${PROFILE_SERVICE_URL:http://localhost:8081}
    notification: ${NOTIFICATION_SERVICE_URL:http://localhost:8083}
    content: ${CONTENT_SERVICE_URL:http://localhost:8082}


management:
  endpoints:
    web:
      exposure:
        include: health,info,caches,metrics
  endpoint:
    health:
      show-details: always
    caches:
      enabled: true
logging:
  level:
    org.springframework.data.neo4j.cypher.deprecation: ERROR
