server:
  port:

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  data:
    mongodb:
      uri: ${MONGODB_URI}

ai:
  openai:
    api-key: ${GEMINI_KEY}
    option:
      model: gemini-2.5-flash
    chat:
      base-url: https://generativelanguage.googleapis.com
      completions-path: v1beta/models/gemini-2.5-flash:generateContent